import { Express } from "express";
import organizationRounter from "./organization.router.js";
import companionRouter from "./companion.router.js";
import parentRouter from "./parent.router.js";
import userOrganizationRouter from "./user-organization.router.js";
import userRouter from "./user.router.js";
import userProfileRouter from "./user-profile.router.js";
import availabilityRouter from "./availability.router.js";
import specialtyRouter from "./speciality.router.js";
import organisationRoomRouter from "./organisation-room.router.js";
import organisationInviteRouter from "./organisation-invite.router.js";
import authUserMobileRouter from "./authUserMobile.router.js";
import coParentInviteRouter from "./coparentInvite.router.js";
import parentCompanionRouter from "./parent-companion.router.js";
import companionOrganisationRouter from "./companion-organisation.router.js";
import docuemntRouter from "./document.router.js";
import serviceRouter from "./service.router.js";
import appointmentRouter from "./appointment.router.js";
import stripeRouter from "./stripe.router.js";
import financeRouter from "./finance.router.js";
import documensoRouter from "./documenso.router.js";
import ratingRouter from "./organisationRating.router.js";
import formRouter from "./form.router.js";
import formAssignmentRouter from "./form-assignment.router.js";
import templateRouter from "./template.router.js";
import templateFhirRouter from "./template.fhir.router.js";
import renderedDocumentFhirRouter from "./rendered-document.fhir.router.js";
import clinicalArtifactFhirRouter from "./clinical-artifact.fhir.router.js";
import prescriptionRouter from "./prescription.router.js";
import expenseRouter from "./expense.router.js";
import deviceTokenRouter from "./deviceToken.router.js";
import chatRouter from "./chat.router.js";
import notificationRouter from "./notification.router.js";
import contactRouter from "./contact-us.router.js";
import accountWithdrawalRouter from "./account-withdrawal.router.js";
import organisationDocumentRouter from "./organisation-document.router.js";
import adverseEventRouter from "./adverse-event.router.js";
import taskRouter from "./task.router.js";
import taskFhirRouter from "./task.fhir.router.js";
import taskScheduleFhirRouter from "./task-schedule.fhir.router.js";
import workspaceRouter from "./workspace.router.js";
import inventoryRoter from "./inventory.router.js";
import searchRouter from "./search.router.js";
import observationToolRouter from "./observationTool.routes.js";
import dashboardRouter from "./dashboard.router.js";
import mobileConfigRouter from "./mobile.config.router.js";
import auditTrailRouter from "./audit-trail.router.js";
import integrationRouter from "./integration.router.js";
import knowledgeRouter from "./knowledge.router.js";
import codeRouter from "./code.router.js";
import labOrderRouter from "./lab-order.router.js";
import labResultRouter from "./lab-result.router.js";
import companionHistoryRouter from "./companion-history.router.js";
import authRouter from "./auth.router.js";
import catalogRouter from "./catalog.router.js";
import healthcareServiceRouter from "./healthcare-service.router.js";
import episodeOfCareRouter from "./episode-of-care.router.js";
import encounterRouter from "./encounter.router.js";
import roomUnitRouter from "./room-unit.router.js";
import roomUnitGroupRouter from "./room-unit-group.router.js";
import marketingUnsubscribeRouter from "./marketing-unsubscribe.router.js";

export function registerRoutes(app: Express) {
  app.use(`/fhir/v1/organization`, organizationRounter);
  app.use(`/fhir/v1/companion`, companionRouter);
  app.use(`/fhir/v1/parent`, parentRouter);
  app.use(`/fhir/v1/user-organization`, userOrganizationRouter);
  app.use(`/fhir/v1/user`, userRouter);
  app.use(`/fhir/v1/user-profile`, userProfileRouter);
  app.use(`/fhir/v1/speciality`, specialtyRouter);
  app.use(`/fhir/v1/organisation-room`, organisationRoomRouter);
  app.use(`/fhir/v1/room-unit`, roomUnitRouter);
  app.use(`/fhir/v1/room-unit-group`, roomUnitGroupRouter);
  app.use(`/fhir/v1/organisation-invites`, organisationInviteRouter);
  app.use(`/fhir/v1/availability`, availabilityRouter);
  app.use(`/v1/authUser`, authUserMobileRouter);
  app.use(`/v1/coparent-invite`, coParentInviteRouter);
  app.use(`/v1/parent-companion`, parentCompanionRouter);
  app.use(`/v1/companion-organisation`, companionOrganisationRouter);
  app.use(`/v1/document`, docuemntRouter);
  app.use(`/fhir/v1/service`, serviceRouter);
  app.use(`/fhir/v1/healthcare-service`, healthcareServiceRouter);
  app.use(`/fhir/v1/appointment`, appointmentRouter);
  app.use(`/fhir/v1/episode-of-care`, episodeOfCareRouter);
  app.use(`/fhir/v1/encounter`, encounterRouter);
  app.use(`/v1/stripe`, stripeRouter);
  app.use(`/v1/finance`, financeRouter);
  app.use(`/v1/documenso`, documensoRouter);
  app.use(`/v1/organisation-rating`, ratingRouter);
  app.use(`/fhir/v1/invoice`, financeRouter);
  app.use(`/fhir/v1/form`, formRouter);
  app.use(`/v1/forms`, formAssignmentRouter);
  app.use(`/fhir/v1/template`, templateFhirRouter);
  app.use(`/fhir/v1/rendered-document`, renderedDocumentFhirRouter);
  app.use(`/fhir/v1/task`, taskFhirRouter);
  app.use(`/fhir/v1/clinical-artifact`, clinicalArtifactFhirRouter);
  app.use(`/fhir/v1/task-schedule`, taskScheduleFhirRouter);
  app.use(`/v1/templates`, templateRouter);
  app.use(`/v1/workspace`, workspaceRouter);
  app.use(`/v1/prescriptions`, prescriptionRouter);
  app.use(`/v1/search`, searchRouter);
  app.use(`/v1/expense`, expenseRouter);
  app.use(`/v1/device-token`, deviceTokenRouter);
  app.use(`/v1/chat`, chatRouter);
  app.use(`/v1/notification`, notificationRouter);
  app.use(`/v1/contact-us`, contactRouter);
  app.use(`/v1/account-withdrawal`, accountWithdrawalRouter);
  app.use(`/v1/organisation-document`, organisationDocumentRouter);
  app.use(`/v1/adverse-event`, adverseEventRouter);
  app.use(`/v1/task`, taskRouter);
  app.use(`/v1/inventory`, inventoryRoter);
  app.use(`/v1/observation-tools`, observationToolRouter);
  app.use(`/v1/dashboard`, dashboardRouter);
  app.use(`/v1/mobile-config`, mobileConfigRouter);
  app.use(`/v1/audit-trail`, auditTrailRouter);
  app.use(`/v1/companion-history`, companionHistoryRouter);
  app.use(`/v1/integration`, integrationRouter);
  app.use(`/v1/knowledge`, knowledgeRouter);
  app.use(`/v1/codes`, codeRouter);
  app.use(`/v1/labs`, labOrderRouter);
  app.use(`/v1/labs`, labResultRouter);
  app.use(`/v1/auth`, authRouter);
  app.use(`/v1/catalog`, catalogRouter);
  app.use(`/v1/email-preferences`, marketingUnsubscribeRouter);
}
